# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$directory$character"

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[➜](bold red)"

[os]
disabled = true
format = "$symbol"

[os.symbols]
Arch = "[ ](fg:bright-blue)"
Debian = "[ ](fg:red)"
EndeavourOS = "[ ](fg:purple)"
Fedora = "[ ](fg:blue)"
NixOS = "[ ](fg:bright-white)"
openSUSE = "[ ](fg:green)"
SUSE = "[ ](fg:green)"


[directory]
format = "[$path](fg:#AAAAAA) "
read_only = "  "
truncation_length = 4
truncation_symbol = "~/…/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
"Projects" = "󱌢 "
"School" = "󰑴 "
"www" = ""
".config" = " "
"dotfiles" = " "

[git_branch]
disabled = true

[docker_context]
disabled = true

[java]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[aws]
disabled = true

